export enum Country {
  Argentina = 'Argentina',
  Bolivia = 'Bolivia',
  Brazil = 'Brazil',
  Chile = 'Chile',
  Colombia = 'Colombia',
  CostaRica = 'Costa Rica',
  Cuba = 'Cuba',
  DominicanRepublic = 'Dominican Republic',
  Ecuador = 'Ecuador',
  ElSalvador = 'El Salvador',
  Guatemala = 'Guatemala',
  Haiti = 'Haiti',
  Honduras = 'Honduras',
  Mexico = 'Mexico',
  Nicaragua = 'Nicaragua',
  Panama = 'Panama',
  Paraguay = 'Paraguay',
  Peru = 'Peru',
  Uruguay = 'Uruguay',
  Venezuela = 'Venezuela',
}
